### PR TITLE
No need for version in header

### PR DESCRIPTION
**Pull request by mnoack**
* Avoids it getting out of date (as it currently is)

### CODE REVIEW

**Comment by mnoack** [comment]
@wiso1234 @MartyWallace - Any update on this PR. Is this repo maintained at the moment (not being negative, just noticed some outstanding PR's and no recent commits). If our company can help maintain in any way let us know.

Also we are looking at extracting smaller components from https://github.com/xodigital/Formerly/pull/65 into PR's into this repo, we understand some of our changes probably are too big so won't be accepted, which is fine.

**Comment by MartyWallace** [comment]
Hi mate, I've left the company that maintains this project and don't want to step on any toes accepting these PR's in their place. I'll try get in touch with someone that's still there are see if they're alright with me handling this for you.

**Comment by mnoack** [comment]
Thanks very much @MartyWallace

**Comment by MartyWallace** [comment]
@mnoack Unfortunately all my contacts have come back saying they no longer work at XO either. I don't even have write access to help you with the outstanding PR's :-(

Hopefully @jwslink or @wiso1234 can help move this along for you.

**Comment by mnoack** [comment]
Thanks @MartyWallace - I've just then sent them an email via their website incase @wiso1234 is perhaps no longer with XO either.

**Comment by AbhishekDas13** [comment]
Hi @mnoack & @MartyWallace,

At the moment XO doesn't have anyone actively maintaining this repo. @wiso1234 has moved on but was pretty keen to maintain it but looks like he seems to be busy these days. I haven't done much with Open sources you guys need to give me some directions here. Would adding you both as collaborators to this repo would help move it forward ? I have pinged @wiso1234 and yet to hear back from him.

**Comment by mnoack** [comment]
Thanks @AbhishekDas13 - I see our company (thus myself and jwslink mainly) being a 'passive maintainer', in other words, where PR's come through and seem reasonable, we'll merge them or ask the requester to do reasonable changes/testing, we won't be actively adding features, more allowing the users of the gem do so by reviewing their PR's.

**Comment by b8ne** [comment]
Hey guys @AbhishekDas13 @mnoack @MartyWallace I've just started working at XO (Enigma) so will try to maintain this package from now on, where time permits.  Im an experienced Laravel dev, so just getting up to speed with Craft.  I dont think I will be able to grant privileges to this repo, however until I get up to speed and can actively test PR's Im happy to trust you guys and merge them if you say they are fine to atleast get something moving again.

**Comment by MartyWallace** [comment]
@b8ne Not sure if the other people you mentioned are in the same boat, but I do not have high enough permissions to accept PRs. Either way, I have very little interest in this project and have no desire to review the outstanding requests :-)

**Comment by mnoack** [comment]
@b8ne - Thanks. Whilst I won't be 'actively' involved, our team is still interested in passively maintaining the repo with others.

You should be able to add as contributors to this repo, or if you're setup as an organisation you should be able to make a new team, which you could call 'formerly', add those who you trust to help, and set the formerly team as being able to access/manage this repository.

If for some reason that can't be done, there is also the option of transferring this repo to someone else OR a new organisation, e.g. 'xocraft' which can house the various craft plugins you guys may have. That could allow others access to those projects you want us access to and separate it from perhaps your private repos you may have.

**Pull request merged**
